
CREATE TABLE IF NOT EXISTS school (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    capacity INT NOT NULL CHECK (capacity BETWEEN 50 AND 2000)
    );

CREATE TABLE IF NOT EXISTS student (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    school_id BIGINT NOT NULL,

    CONSTRAINT fk_school
    FOREIGN KEY (school_id)
    REFERENCES school(id)
    ON DELETE RESTRICT
    );
