version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shalion-school
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shalion
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/init-db:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: shalion-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DOCKER_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
